function [ x_out ] = trmv_ut_unb_var1( U, x )

  [ UL, UR ] = FLA_Part_1x2( U, ...
                               0, 'FLA_LEFT' );

  [ xT, ...
    xB ] = FLA_Part_2x1( x, ...
                         0, 'FLA_TOP' );

  while ( size( UL, 2 ) < size( U, 2 ) )

    [ U0, u1, U2 ]= FLA_Repart_1x2_to_1x3( UL, UR, ...
                                         1, 'FLA_RIGHT' );

    [ x0, ...
      chi1, ...
      x2 ] = FLA_Repart_2x1_to_3x1( xT, ...
                                    xB, ...
                                    1, 'FLA_BOTTOM' );

    %------------------------------------------------------------%

    chi1 = laff_dot(u1, x);

    %------------------------------------------------------------%

    [ UL, UR ] = FLA_Cont_with_1x3_to_1x2( U0, u1, U2, ...
                                           'FLA_LEFT' );

    [ xT, ...
      xB ] = FLA_Cont_with_3x1_to_2x1( x0, ...
                                       chi1, ...
                                       x2, ...
                                       'FLA_TOP' );

  end

  x_out = [ xT
            xB ];

return
