function [ y_out ] = trmvp_lt_unb_var2( L, x, y )

  [ LT, ...
    LB ] = FLA_Part_2x1( L, ...
                         0, 'FLA_TOP' );

  [ xT, ...
    xB ] = FLA_Part_2x1( x, ...
                         0, 'FLA_TOP' );

  while ( size( LT, 1 ) < size( L, 1 ) )

    [ L0, ...
      l1t, ...
      L2 ] = FLA_Repart_2x1_to_3x1( LT, ...
                                    LB, ...
                                    1, 'FLA_BOTTOM' );

    [ x0, ...
      chi1, ...
      x2 ] = FLA_Repart_2x1_to_3x1( xT, ...
                                    xB, ...
                                    1, 'FLA_BOTTOM' );

    %------------------------------------------------------------%

    y = laff_axpy(chi1, l1t, y);

    %------------------------------------------------------------%

    [ LT, ...
      LB ] = FLA_Cont_with_3x1_to_2x1( L0, ...
                                       l1t, ...
                                       L2, ...
                                       'FLA_TOP' );

    [ xT, ...
      xB ] = FLA_Cont_with_3x1_to_2x1( x0, ...
                                       chi1, ...
                                       x2, ...
                                       'FLA_TOP' );

  end

  y_out = y;


return
