function [ y_out ] = trmvp_ut_unb_var2( U, x, y )

  [ UT, ...
    UB ] = FLA_Part_2x1( U, ...
                         0, 'FLA_TOP' );

  [ xT, ...
    xB ] = FLA_Part_2x1( x, ...
                         0, 'FLA_TOP' );

  while ( size( UT, 1 ) < size( U, 1 ) )

    [ U0, ...
      u1t, ...
      U2 ] = FLA_Repart_2x1_to_3x1( UT, ...
                                    UB, ...
                                    1, 'FLA_BOTTOM' );

    [ x0, ...
      chi1, ...
      x2 ] = FLA_Repart_2x1_to_3x1( xT, ...
                                    xB, ...
                                    1, 'FLA_BOTTOM' );

    %------------------------------------------------------------%

    y = laff_axpy(chi1, u1t, y);

    %------------------------------------------------------------%

    [ UT, ...
      UB ] = FLA_Cont_with_3x1_to_2x1( U0, ...
                                       u1t, ...
                                       U2, ...
                                       'FLA_TOP' );

    [ xT, ...
      xB ] = FLA_Cont_with_3x1_to_2x1( x0, ...
                                       chi1, ...
                                       x2, ...
                                       'FLA_TOP' );

  end

  y_out = y;


return
