function [ y_out ] = trmvp_lt_unb_var1( L, x, y )

  [ LL, LR ] = FLA_Part_1x2( L, ...
                               0, 'FLA_LEFT' );

  [ yT, ...
    yB ] = FLA_Part_2x1( y, ...
                         0, 'FLA_TOP' );

  while ( size( LL, 2 ) < size( L, 2 ) )

    [ L0, l1, L2 ]= FLA_Repart_1x2_to_1x3( LL, LR, ...
                                         1, 'FLA_RIGHT' );

    [ y0, ...
      psi1, ...
      y2 ] = FLA_Repart_2x1_to_3x1( yT, ...
                                    yB, ...
                                    1, 'FLA_BOTTOM' );

    %------------------------------------------------------------%

    psi1 = laff_dot(l1, x) + psi1;

    %------------------------------------------------------------%

    [ LL, LR ] = FLA_Cont_with_1x3_to_1x2( L0, l1, L2, ...
                                           'FLA_LEFT' );

    [ yT, ...
      yB ] = FLA_Cont_with_3x1_to_2x1( y0, ...
                                       psi1, ...
                                       y2, ...
                                       'FLA_TOP' );

  end

  y_out = [ yT
            yB ];

return
