function [ y_out ] = trmvp_ut_unb_var1( U, x, y )

  [ UL, UR ] = FLA_Part_1x2( U, ...
                               0, 'FLA_LEFT' );

  [ yT, ...
    yB ] = FLA_Part_2x1( y, ...
                         0, 'FLA_TOP' );

  while ( size( UL, 2 ) < size( U, 2 ) )

    [ U0, u1, U2 ]= FLA_Repart_1x2_to_1x3( UL, UR, ...
                                         1, 'FLA_RIGHT' );

    [ y0, ...
      psi1, ...
      y2 ] = FLA_Repart_2x1_to_3x1( yT, ...
                                    yB, ...
                                    1, 'FLA_BOTTOM' );

    %------------------------------------------------------------%

    psi1 = laff_dot(u1, x) + psi1;

    %------------------------------------------------------------%

    [ UL, UR ] = FLA_Cont_with_1x3_to_1x2( U0, u1, U2, ...
                                           'FLA_LEFT' );

    [ yT, ...
      yB ] = FLA_Cont_with_3x1_to_2x1( y0, ...
                                       psi1, ...
                                       y2, ...
                                       'FLA_TOP' );

  end

  y_out = [ yT
            yB ];

return

